"""
Service generation module - generates microservice code from user ideas.
"""
import os
from dataclasses import dataclass
from typing import Optional


@dataclass
class GeneratedService:
    """Represents a generated microservice."""
    
    service_id: str
    code: str
    dependencies: list[str]
    readme: str
    dockerfile: str


class ServiceGenerator:
    """Generates microservice code from natural language descriptions."""
    
    def __init__(self, llm_api_key: Optional[str] = None):
        self.llm_api_key = llm_api_key or os.getenv("OPENAI_API_KEY")
        
    def generate(self, idea: str, service_id: str) -> GeneratedService:
        """
        Generate a microservice from a user's idea.
        
        Args:
            idea: Natural language description of the service
            service_id: Unique identifier for this service
            
        Returns:
            GeneratedService with code, dependencies, and deployment files
        """
        # For MVP: Generate a simple FastAPI service template
        # TODO: Integrate with LLM for custom generation
        
        code = self._generate_service_code(idea, service_id)
        dependencies = self._generate_dependencies()
        readme = self._generate_readme(idea, service_id)
        dockerfile = self._generate_dockerfile()
        
        return GeneratedService(
            service_id=service_id,
            code=code,
            dependencies=dependencies,
            readme=readme,
            dockerfile=dockerfile
        )
    
    def _generate_service_code(self, idea: str, service_id: str) -> str:
        """Generate the main service code."""
        return f'''"""
{service_id} - Generated microservice
User idea: {idea}
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="{service_id}")


class RequestData(BaseModel):
    """Request payload for this service."""
    input: str


class ResponseData(BaseModel):
    """Response payload for this service."""
    output: str
    service_id: str


@app.get("/")
def root():
    """Health check and service info."""
    return {{
        "service_id": "{service_id}",
        "status": "running",
        "description": "{idea}"
    }}


@app.post("/process", response_model=ResponseData)
def process(data: RequestData) -> ResponseData:
    """
    Main service endpoint.
    
    User request: {idea}
    """
    # TODO: Implement actual business logic
    result = f"Processed: {{data.input}}"
    
    return ResponseData(
        output=result,
        service_id="{service_id}"
    )


@app.get("/health")
def health():
    """Health check endpoint."""
    return {{"status": "healthy"}}
'''
    
    def _generate_dependencies(self) -> list[str]:
        """Generate requirements.txt dependencies."""
        return [
            "fastapi>=0.110.0",
            "uvicorn[standard]>=0.27.0",
            "pydantic>=2.6.0"
        ]
    
    def _generate_readme(self, idea: str, service_id: str) -> str:
        """Generate README for the service."""
        return f'''# {service_id}

**Generated by Microservices Factory**

## Description

{idea}

## API Endpoints

### GET /
Service info and health check

### POST /process
Main processing endpoint

**Request:**
```json
{{
  "input": "your data here"
}}
```

**Response:**
```json
{{
  "output": "processed result",
  "service_id": "{service_id}"
}}
```

### GET /health
Health check

## Running Locally

```bash
pip install -r requirements.txt
uvicorn main:app --reload
```

## Deployment

This service is deployed via Microservices Factory.
Access requires holding the service's token.

## Token Address

`[Set after token creation]`
'''
    
    def _generate_dockerfile(self) -> str:
        """Generate Dockerfile for deployment."""
        return '''FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''
